# Generated by Django 4.1 on 2022-10-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_profile_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='query',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='slug',
            new_name='tagline',
        ),
    ]
